### ISSUE TITLE
Consider refactoring `modifyState` back to tokens, but use a different term to refer to the concept

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-hooks#30]
I gotta say... I'm really not liking this `useGet` pattern... It feels very verbose to me since it forces every usage of a `useState` to have a corresponding `useGet`. Moreover, I think it affects performance because now every function call requires you to pass in an additional argument to a function. If a function required two state tokens to fully implement it in `v0.2.1`, it now requires 2-4 in `v0.3.0`. Otherwise, one cannot read the value in a handler if it's needed. This especially doesn't scale well in libraries like `halogen-select` where this happens repeatedly. 
Lastly, it no longer parallels the `H.put`, `H.get`, `H.modify_`, `H.modify` `HalogenM` code we're already used to.

```purescript
-- v0.2.1
foo = Hooks.do
 state /\ stateToken <- useState 0
 Hooks.pure
  HH.button 
    [ HH.onClick \_ -> Just $ dofoo ]
    [ HH.text $ "State is: " <> show state ]
  where
    doFoo stateToken = do
      st <- H.get stateToken
      when (st < 4) $ H.modify_ stateToken (_ + 1)

-- v0.3.0
foo = Hooks.do
 state /\ modifyState <- useState 0
 getState <- useGet state
 Hooks.pure
  HH.button 
    [ HH.onClick \_ -> Just $ dofoo getState modifyState
    [ HH.text $ "State is: " <> show state ]
  where
    doFoo getState modifyState = do
      st <- getState
      when (st < 4) $ modifyState (_ + 1)
```

The `v0.3.0` code's approach wouldn't be as problematic if `modifyState` returned the updated value (e.g. its type signature was changed to `(State -> State) -> HookM m State`). However, I imagine that "getting" the latest value via this approach (i.e. `value <- modifyState identity`) would always modify state; thus, it would always trigger `useTickEffect` memo-rechecking. Even if not, it's misleading that one has to `modifyState` to "get" the value.

I almost want something like this:
```purescript
foo = Hooks.do
 -- Int /\ { get :: HookM m Int, put :: Int -> HookM m Unit }
 state /\ stateRec <- useState 0
 Hooks.pure
  HH.button 
    [ HH.onClick \_ -> Just $ dofoo stateRec
    [ HH.text $ "State is: " <> show state ]
  where
    doFoo stateRec = do
      st <- stateRec.get
      when (st < 4) $ stateRec.put (st + 1)
```
However, recovering `modify`/`modify_` would suck:
```purescript
stateRec.get >>= stateRec.put <<< _ + 1
```
One could resupport all of the state functions via a record, but I'm not sure what its overhead would be, especially since not all of them would be used.
```purescript
state /\ { get, put, modify, modify_ } <- useState 0
```

I think your original token-based idea was the better approach for the following reasons:
- it's similar to HalogenM's corresponding code, so it's familiar
- a function's number of arguments doesn't grow as quickly
- it's more performant than the Record-based idea above because we don't allocate functions that we might never use

So, I'm reexamining the [reasons why you changed this approach previously](https://github.com/thomashoneyman/purescript-halogen-hooks/pull/29#issue-414346312). If I were to summarize them, it would be:
1. It's similar to `modify_` and React Hooks' corresponding usage
2. Tokens are purely a way to opt-in to component features
3. Explaining what Tokens are is hard, but a function is easier to understand
4. People were using different naming conventions
5. An `input` value can go stale, so why not use the same approach for both stale `input` values and `state` values? 

I'd like to respond to these. 
1. While it may be similar, it's actually harder / more annoying to use in practice for the reasons I raise above.
2. (and 3). Tokens can still be "purely a way to opt-in to component features." If you reverted back to your "array index hidden behind a type" approach in v0.2.1, you could call them something different than Tokens. For example, `StateIndex` might make more sense and still be easy to explain: "a `StateIndex` is just the index of the corresponding slot in the backing array. Calling `get`, `put`, `modify`, etc. need this index to ensure you're modifying the correct one. This index value is wrapped in a special type to make type inference work better and prevent misuse of the value (e.g. incrementing it by one and modifying the wrong element in the array)." In other words, this might be a documentation issue, not a "change the implementation/approach" issue.
4. True. Perhaps we should ask those people why they did that and come to an agreement about what naming convention to recommend? For example, I value short names for bindings, readability by keeping the name of the token binding as close to the name of the real value as possible, and auto-complete-friendly names by making it easy to refer to the token, not the actual value (or vice versa). Thus, I reached my `t`-prefixing idea. Even if agreement is not reached, at the end of the day, does it really matter? We're still all using the same type signature, so if we misuse that, a compiler error will point us in the right direction.
5. Stale values should be fixed by `useGet`, which works for both `input`s and `state`s. That doesn't mean we need to switch to this `modifyState` approach.

**Comment by thomashoneyman** [comment]
Thanks for the feedback! I think the situation is a little better than described here, but even so it may not work as well for you as the previous StateToken approach.

> It feels very verbose to me since it forces every usage of a useState to have a corresponding useGet.

This isn't true; you only need `useGet` if you might end up referring to stale state. In the code you shared as an example:

```purs
-- v0.3.0
foo = Hooks.do
  state /\ modifyState <- useState 0
  getState <- useGet state
  Hooks.pure $ ... [ HE.onClick \_ -> Just $ doFoo getState modifyState ]
  where
  doFoo getState modifyState = do
    st <- getState
    when (st < 4) $ modifyState (_ + 1)
```

could have been written without `getState` by passing the state through directly:

```purs
-- v0.3.0
foo = Hooks.do
  state /\ modifyState <- useState 0
  Hooks.pure $ ... [ HE.onClick \_ -> Just $ doFoo state modifyState ]
  where
  doFoo state modifyState = do
    when (state < 4) $ modifyState (_ + 1)
```

or, as is more common in the Hooks code I've seen in the wild, by defining `doFoo` in a `let` block instead -- this is what you would usually do, although I agree that for components with a ton of these like Select you might want to pull them out into `where` instead:

```purs
-- v0.3.0
foo = Hooks.do
  state /\ modifyState <- useState 0
  let doFoo = when (state < 4) $ modifyState (_ + 1)
  Hooks.pure $ ... [ HE.onClick \_ -> Just doFoo ]
```

Before we talk more about your other points, does this clear up at least the problem of having to use `useGet` all over the place? And, if so, do you still advocate for a return to the token?

**Comment by JordanMartinez** [comment]
> Before we talk more about your other points, does this clear up at least the problem of having to use useGet all over the place?

In hindsight, I'm not sure why I didn't do that. Perhaps because it guarantees that no stale state can occur...? (It was also late, so maybe I wasn't thinking straight anymore). I understand that `useGet` is only necessary when you define a computation in one hook evaluation cycle that won't run until some later hook evaluation cycle. Thus, for most cases, you can just use the `state` value returned by `useState`. 

> And, if so, do you still advocate for a return to the token?

Yes, I still advocate for a return to the token approach for four reasons. 

First, the current `modifyState` approach still does not address my concern regarding the number of function arguments increasing faster in the current approach than in the token approach. This isn't an issue when using `let` bindings as one can refer to these things in-scope. However, it does matter when one uses `where` bindings. In hooks that require more complexity (e.g. `halogen-select`), `where` bindings would make the hook more readable. Or, looking forward, how much will this affect `halogen-formless` when we get to it?

Second, I prefer the token approach because, correct me if I'm wrong but, I believe that the `H.get stateToken` always gets the current state value, regardless of "when" the computation is defined and "when" it is run. Cognitively, I think it's easier for the developer to not have to worry about stale state values (e.g. "do I use `state` here or the `useGet`-and-`getState` pattern?). So, if the token-based approach would prevent that, it would lead to less bugs. Now, one would still need to use `useGet` to prevent a stale input value, but I wonder if that could exist as its own `HookM` code, `H.getInput`, rather than needing to use a `useGet` in the first place.

Third, `H.get stateToken` does not require paying for a `useRef` hook used internally by `useGet`. If one uses a hook-based component that composes multiple hooks, this doesn't scale well and affects performance (based on the as-yet-unproven principle that "less hooks used = more performant component"). 

Four, `H.get`, `H.put`, `H.modify`, `H.modify_` just work better with this approach and are similar to the `HalogenM` code. While I can write `modifyState $ const 4`, `H.put stateToken 4` is more straightforward.

**Comment by thomashoneyman** [comment]
> First, the current modifyState approach still does not address my concern regarding the number of function arguments increasing faster in the current approach than in the token approach.

Yes, using `modifyState` means that a function which needs both a) the state and b) to modify the state would end up getting both of these as arguments, instead of getting only the state token before. This is more arguments than you'd have otherwise (though if you only need to modify state, or you only need the current state, you're still at one argument).

That said, I find this one a little less convincing simply because I think you'll find Hooks lend themselves much better to `let` over `where` to keep things in scope. In our large codebase we generally only move things using `captures` into `where` clauses, and helper functions out of the component altogether.

> Second, I prefer the token approach because, correct me if I'm wrong but, I believe that the `H.get stateToken` always gets the current state value, regardless of "when" the computation is defined and "when" it is run.

This is a good point; as a developer you can always use `H.get` to get the current value even if you are unsure whether you need to. I think you still end up with the question "Should I `get` the state, or use the existing state?" but erring on the side of getting the state anyway is pretty safe.

> Cognitively, I think it's easier for the developer to not have to worry about stale state values (e.g. "do I use `state` here or the `useGet-and-getState` pattern?).

This is why I was OK with switching in the first place: I could be off, but I really don't think you need to ask this question in the vast majority of cases. It's pretty much only when you are doing an effect cleanup or some forked computation, and those tend to be pretty obvious. Thinking again of our large codebase at work, actually needing to call `getState` is really, really rare (this is in a React codebase, and React Hooks don't have `get`).

Effect cleanup is the most common place where you'll have to worry about this, but effect cleanup is pretty uncommon. Effects tied to a render doesn't exist in standard Halogen, and the most common thing to do in a finalizer is end a subscription -- and you can just pass through the `SubscriptionId` as a function argument when writing `useLifecycleEffect`, skipping state altogether. The only effect cleanup I've seen in Halogen Hooks so far consists of ending subscriptions or writing refs.

All of this is to say that you make a good point: it _is_ easier for the developer to never have to worry about stale state values, but, if stale state values are really uncommon, then how much should this be prioritized?

> Third, `H.get stateToken` does not require paying for a `useRef` hook used internally by `useGet`. 

This is the most compelling reason for switching back, in my opinion, because this truly is an unnecessary penalty. The call to `useRef` is cheap, and so is evaluating the post-render effect to write the ref, but it's a shame to incur this when you already had `get` available via the regular Halogen library.

Once again this, for me, comes down to the question: how often would this be used in practice?

`Hooks.getInput` is a good point, too -- we do have the input in state, so we _could_ read it and give that as a function to the end user instead of having them use `useGet`.

**Comment by thomashoneyman** [comment]
This does leave some options available:

1. Revert to the previous `useState` which returned a token for use with `modify_`, `modify`, `put`, and `get`, which allows you to skip `getState` in the rare cases where it would otherwise be necessary, and use `put` or `modify` if you want to.

2. Provide both `useState` (returning a modify function) and another interface like `useStateToken` (returns the value and the token) or `useStateFunctions` (returns the value and `get`, `put`, `modify_`, `modify`) or something else which could be used if there were risk of stale state in a given scenario and we want to avoid forcing `useGet`.

3. Stay with just `useState` returning a modify function.

4. Other options?

Right now I'm a bit on the fence about which option I'd prefer.

I don't feel as strongly that `modifyState` is a problem specifically because:

* I think stale state is a pretty rare occurrence, and so `getState` isn't common either.
* The vast majority of states in Halogen components are records (which is also true of states in React Hooks, which we use at work) and I don't mind `modifyState _ { override = ... }` and `modifyState \_ -> { put: ... }` for `modify_` and `put`.
* I do appreciate the simplicity of getting a modify function back instead of a token to pass to other state functions from HalogenM.

But I recognize that the simplicity of `modifyState` (in my opinion) is marred by a few things:

* It causes you to give up on the perfectly usable `Hooks.get` in favor of a clunky workaround, `useGet`, for when you _do_ need to worry about stale state.
* If you don't like `modifyState \_ -> x` or `modifyState <<< const`, then you're being stopped from using `put` unecessarily.
* Tokens probably aren't that bad to learn about anyway, so what's the problem?

**Comment by JordanMartinez** [comment]
> That said, I find this one a little less convincing simply because I think you'll find Hooks lend themselves much better to let over where to keep things in scope. In our large codebase we generally only move things using captures into where clauses, and helper functions out of the component altogether.

I agree that `let` blocks are easier to write for because it has everything in scope. In one way, they are more "readable" than using `where` blocks because we don't need to pass in the token/`modifyState`.  However, using `let` blocks are also less readable when trying to understand the hook as a whole. For example, in my PR for `halogen-select`, I originally wrote it as a `let` block because it was easier to migrate the library to Hooks via that approach. However, there was a lot of content in the `let` block between the first `useState` hook and the last `Hooks.pure { toggleProps, containerProps }` hook. By switching it to a `where` block, it's easier to understand the whole hook because there are only 3 parts: the main hook implementation, the functions the props use, the implementations of those props.

> This is a good point; as a developer you can always use H.get to get the current value even if you are unsure whether you need to. I think you still end up with the question "Should I get the state, or use the existing state?" but erring on the side of getting the state anyway is pretty safe.

True, the original question (i.e. "Do I use `state` here or the X pattern?" where X depends on which approach we use) still remains regardless of which approach we use. Honestly, I think this will be a documentation issue. Those who learned Halogen before being exposed to Halogen Hooks will likely default to using `H.get` because that's what they would do when writing the code for handling actions or queries. However, there's nothing stopping them from using `state` itself. They might even prefer that.

> This is why I was OK with switching in the first place: I could be off, but I really don't think you need to ask this question in the vast majority of cases. It's pretty much only when you are doing an effect cleanup or some forked computation, and those tend to be pretty obvious.

I agree that this issue only arises when doing Effect cleanup or doing some forked computation in Aff. 

> This does leave some options available:

Regarding your comment on the second option. It sounds like you're suggesting two hooks: `useState` and `useStateToken` that do the same thing but provide two different interfaces. In some ways, that could work because it allows the end-user to choose which they use. In other ways, I think it's not a good solution. If two libraries used by an end-user each use one of them, the developer must now ask, "Do I use `useGet` or `H.get stateToken`? Do I use `modifyState` or `H.modify_ stateToken`?"

**Comment by JordanMartinez** [comment]
Anyways, here is my current understanding of the issue:
- **Documentation:** regardless of which approach we use, it is still possible for one to refer to stale state/input values in an Effect cleanup / forked Aff computation. This can only be prevented by good documentation.
- **Performance:** while the token-based approach does not require using an unneeded `useRef`, does this happen frequently enough that the hit to an app's performance is actually relevant?
- **Readability:** which is easier to read: `let` blocks where everything is in scope (i.e. readable function implementations are prioritized over whole-hook understanding) or `where` blocks where functions take explicit arguments (i.e. readable whole-hook understanding is prioritized over readable function implementations).
- **Syntax A:** which is more/less annoying, `getState <- useGet state` or `H.get stateToken`?
- **Syntax B:** which is more/less annoying, `modifyState (_ { foo = 1})` or `H.modify_ fooToken (_ { foo = 1 })`
- **Syntax C:** which is more/less annoying, `modifyState $ const 1` or `H.put stateToken 1`?
- **Interface:** should we commit to one approach, or support both?

**Comment by JordanMartinez** [comment]
One other question about the current `modifyState` approach...

If a hook like `halogen-select` does not use `useGet`, then the actions it returns cannot be used in a forked computation or Effect cleanup, correct? Otherwise, any state values to which it refers would always be stale at that point, right?

**Comment by JordanMartinez** [comment]
Just another thought.
If we use the token-based approach, we can still get the `modifyState` approach by using an Indexed Bifunctor type class' `irmap` (i.e. indexed `rmap`).
```purescript
state /\ modifyState <- irmap Hooks.modify_ $ useState 1
```
AFAIK, the current approach cannot be used to reimplement the token-based approach.

**Comment by thomashoneyman** [comment]
Thanks for your thoughtful comments, @JordanMartinez. I’ve come around to reverting back to a token approach and thanks for thinking through this with me. Here’s what I suggest:

1. Re-introduce `modify`, `modify_`, `put`, and `get` via a unique identifier returned by the `useState` hook. This identifier has the type `StateId` and the style I’d probably use is `state /\ stateId`.
2. Update the documentation on stale state to refer to `get` and remove the `useGet` example. Note that you can store input in a mutable reference if you need to refer to it later.
4. Notify users that if they want to recover the previous `modifyState` function they can use `imap (map Hooks.modify_)` on the `useState` hook to accomplish the same thing. This should have been the update I made in the first place. Users who want this to be the default way to use the `useState` hook should make their own `Hooks` module which exports this modified `useState` for use throughout their code.

With regards to your points:

**Documentation:** The documentation on when you cannot use the state value returned by `useState` will stay in place, but will refer to `Hooks.get stateId` instead.

**Performance:** I still don’t think `useGet` would be used commonly enough to be worried about performance, but it’s a bit silly to introduce a performance hit completely unnecessarily — given that you can just do `imap (map Hooks.modify_)` to get the same behavior.

**Syntax:** Since you can still do either one via `imap (map Hooks.modify_)` this isn’t really a problem.

**Interface:** One interface is enough!

> One other question about the current modifyState approach… If a hook like halogen-select does not use useGet, then the actions it returns cannot be used in a forked computation or Effect cleanup, correct? Otherwise, any state values to which it refers would always be stale at that point, right?

This question is still relevant if you have `get` available. If a hook returns a `HookM` computation that closes over a `state` variable, then it can’t be used in an effect cleanup or forked computation in the consumer. Keep in mind that `modify` always uses fresh state, though, so it’s really only if you needed to get the state and do something effectful with it.

> If we use the token-based approach, we can still get the modifyState approach by using an Indexed Bifunctor type class’ irmap (i.e. indexed rmap).

Yes, `irmap` or `imap` work fine. I really should have caught that in the original PR.

```purs
state /\ modifyState <- imap (map Hooks.modify_) $ useState 1
```

This is the biggest reason, to me, to revert the change. You still get to use `get` whenever you want, you can use `put` and friends if you want, and if you want to get the simple `modifyState` that’s trivial, too.

I still will prefer to use `modifyState` in general, but it was a mistake to rush to simplify things via this restriction.

> Now, one would still need to use useGet to prevent a stale input value, but I wonder if that could exist as its own HookM code, H.getInput, rather than needing to use a useGet in the first place.

This _can_ exist, not as an arbitrary `HookM m input` function, but as something the `component` function returns to you (the same way it returns tokens). You don't know the input type until you make the component. I'm not sure I want to make this function every time you make a component, though; given the rarity of needing to do this you're probably better off just copying the bit of input you need into a mutable reference anyway.

**Comment by JordanMartinez** [comment]
Hurray!

> Users who want this to be the default way to use the useState hook should make their own Hooks module which exports this modified useState for use throughout their code.

I think I'll add this to Halogen Hooks Extra. Maybe as `useModifyState`? The name should be different enough that most people won't confuse it with `useState`.

> This can exist, not as an arbitrary HookM m input function, but as something the component function returns to you (the same way it returns tokens). You don't know the input type until you make the component. I'm not sure I want to make this function every time you make a component, though; given the rarity of needing to do this you're probably better off just copying the bit of input you need into a mutable reference anyway.

That's fair.

**Comment by thomashoneyman** [comment]
> I think I'll add this to `Halogen Hooks Extra`. Maybe as `useModifyState`? The name should be different enough that most people won't confuse it with useState.

I added it in the examples as `useStateFn` and defined it so that you can pass in whatever state function you want:

```purs
useStateFn fn initial = map (map fn) (useState initial)

Hooks.do
  _ /\ setState <- useStateFn Hooks.put 0
  _ /\ modifyState <- useStateFn Hooks.modify_ 0
```

which could easily be turned into `useModifyState` and `useSetState` for convenience.

**Comment by JordanMartinez** [comment]
Ah, good idea.
