### ISSUE TITLE
Button and Container example not working outside of storybook

### ISSUE THREAD

**Issue by milesfrain** [thomashoneyman/purescript-halogen-hooks#36]
After copying this [Button and Container example](https://github.com/thomashoneyman/purescript-halogen-hooks/tree/master/examples/Example/Halogen/Components) to a halogen template, queries to the child component are no longer working. The parent always says the button is off, even when the label changes.

The only different I can think of is how the component is being launched:
```purs
main :: Effect Unit
main = HA.runHalogenAff do
  body <- HA.awaitBody
  runUI Container.component unit bod
```
I wouldn't expect running `Effect` in `Aff` would cause problems.

Here's the template branch with the broken example.
https://github.com/milesfrain/halogen/tree/container/src
Reproduce with:
```
npm run serve
```

**Comment by thomashoneyman** [comment]
This is happening because the [Hooks is at version 0.2.0 in the package set](https://github.com/purescript/package-sets/blob/4f72f840fdc80e9b793476dc684289502c6ee05f/src/groups/thomashoneyman.dhall#L12-L16) for that repository (the May 7 package set).

In that version of Hooks the `useQuery` handler was only defined on initialize, and not on every render. That meant it worked fine if you used `Hooks.get` internally, but if you referred to a state variable directly it would get stale over the subsequent renders.

```purs
  enabled <- Hooks.useState false
  Hooks.useQuery tokens.queryToken case _ of
    IsOn reply -> do
      pure (Just (reply enabled))
```

Here, `enabled` is `false` on the first render, and the `useQuery` handler closes over the value. So the same handler, now essentially hardcoded to return `false`, gets called on any query. The current version of Hooks (0.4.0) handles this differently: on every render the `useQuery` handler is refreshed, so there's no issue with closing over values like `enabled` here.

If you update to the current version of Hooks (0.4.0) -- which is in the current package set, but the package set hasn't yet had a new release -- then your example should work again. Alternately, you can do this:

```purs
  Hooks.useQuery tokens.queryToken case _ of
    IsOn reply -> do
      enabled' <- Hooks.get enabledId
      pure (Just (reply enabled'))
```

**Comment by milesfrain** [comment]
Thanks. I installed the latest by manually adding to packages.dhall as described [here](https://github.com/thomashoneyman/purescript-halogen-hooks#installation), and it now works.
