### ISSUE TITLE
Push docs to Pursuit

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-hooks#45]
Now that `pulp` doesn't check whether a repo is in the Bower registry (only whether it's in the `purescript/registry` registry), you can now upload this repo's docs to Pursuit.

You might as well update Halogen to the v5.0.0 stable release, too.

**Comment by thomashoneyman** [comment]
I just tried to do this with the current `master`, but Pulp seems to be failing to find built files on my system at the moment. I don't have time to debug further at the moment -- since anyone can upload docs, would you mind giving it a try?

I've [published the v0.4.3 release](https://github.com/thomashoneyman/purescript-halogen-hooks/releases/tag/v0.4.3).

**Comment by JordanMartinez** [comment]
Done! https://pursuit.purescript.org/packages/purescript-halogen-hooks/0.4.3

I ran the following to get that
```bash
git checkout v0.4.3
bower i
pulp publish --no-push
```

**Comment by thomashoneyman** [comment]
Thank you!

**Comment by JordanMartinez** [comment]
I'll need to make a new release referring to this version on my side of things, and then any links I have to your docs will work. Right now, they don't exist on Pursuit.

Glad to help!
