### ISSUE TITLE
Consider absorbing `use*State` convenience functions from Hooks.Extra

### ISSUE THREAD

**Issue by milesfrain** [thomashoneyman/purescript-halogen-hooks#50]
It took me a while to notice:
1. [This section](https://github.com/thomashoneyman/purescript-halogen-hooks/blob/master/docs/01-Hooks-At-A-Glance.md#using-a-modify-function-instead-of-an-identifier) on `useStateFn`
1. [`useStateFn`](https://pursuit.purescript.org/packages/purescript-halogen-hooks-extra/0.6.3/docs/Halogen.Hooks.Extra.Hooks.UseStateFn#v:useStateFn) is available in Hooks.Extra
1. Hooks.Extra also has [`useModifyState`](https://pursuit.purescript.org/packages/purescript-halogen-hooks-extra/0.6.3/docs/Halogen.Hooks.Extra.Hooks.UseStateFn#v:useModifyState)

These convenience functions are handy enough to include in this repo, but I'd also be happy with them in Hooks.Extra if they're featured in the docs for easier discoverability. That would help make this API match the conciseness of react-hooks-basic (as discussed in #30).

Related PR: https://github.com/JordanMartinez/purescript-halogen-hooks-extra/pull/7

**Comment by thomashoneyman** [comment]
As discussed in #30 I would like to keep this repository to a single `useState`, and defer the various ways that you can modify that call to produce other Hooks to the documentation and to other libraries like hooks-extra.

I've been reluctant to link out to external libraries because it means that the documentation can get out of date if the other libraries update, but I think it's harmless to at least link to hooks-extra and note that it includes implementations of `useStateFn`, `useModifyState`, etc.

**Comment by JordanMartinez** [comment]
> I think it's harmless to at least link to hooks-extra and note that it includes implementations of useStateFn, useModifyState, etc.

That should be fine. I doubt those implementations will be going anywhere anytime soon.
