### ISSUE TITLE
question - is there something holding up releasing latest version here?

### ISSUE THREAD

**Issue by afcondon** [thomashoneyman/purescript-halogen-hooks#67]
Spago install gives you 0.4.3 but (i think, maybe i'm making big mistake here) that all the examples and so on are already updated to use the big changes from September ("single index for hook types") and so you can't use those examples as a basis for explorations via the low-effort route of `spago install halogen-hooks`

Obviously, there are workarounds, but i just thought i'd ask here in case i've either misunderstood or something failed to get published that should have been published.

**Comment by thomashoneyman** [comment]
I intended to release the next version of Hooks along with the related 0.14 updates for the PureScript compiler. That's because the 0.14 version of the compiler doesn't require the weird workarounds with `HookNewtype` in order to write your hook types and I'd rather not have anyone write those if they can avoid it.

0.14 is right around the corner, and Hooks will be updated alongside Halogen. So I would anticipate a new release of this library soon. In the meantime I'd recommend either adding Hooks as an override to your `packages.dhall` file or browsing this repository at the 0.4.3 tag.

Sorry about the hassle!

**Comment by afcondon** [comment]
that's totally fine with me
